GenerateNU/dearly

- README.md
- docs/ARCHITECTURE.md
> docs: add links to the docs

- docs/ARCHITECTURE.md
> docs: minor fix ARCHITECTURE.md

- .github/dependabot.yml
- docs/ARCHITECTURE.md
> ci: remove tailwind from dependabot update

- .github/dependabot.yml
- backend/src/utilities/errors/app-error.ts
- docs/ARCHITECTURE.md
> fix: app error handling

- backend/src/tests/helpers/test-builder.ts
- backend/src/tests/user/delete.test.ts
- backend/src/tests/user/full.test.ts
- docs/BACKEND.md
> refactor test builder & update test docs

- README.md
- backend/src/tests/helpers/test-builder.ts
- backend/src/tests/user/delete.test.ts
- backend/src/tests/user/full.test.ts
- docs/BACKEND.md
> add repobeats to README.md

- CONTRIBUTING.md
- backend/src/utilities/docs.ts
> Add potentially helpful command for sql debugging

- backend/package.json
- backend/scripts/codegen.sh
- backend/scripts/generate.ts
- backend/src/entities/users/controller.ts
- backend/src/types/api/routes/users.ts
- backend/src/types/api/schemas/users.ts
> Add Cleanup and typechecking

- backend/src/types/api/routes/users.ts
> Fix naming issue

- backend/src/constants/db-error.ts
- backend/src/middlewares/auth.ts
- backend/src/tests/server/auth.test.ts
- backend/src/utilities/errors/db-error.ts
- backend/src/utilities/errors/service-error.ts
> fix: auth middleware and database error zod

- frontend/app/(auth)/components/register-form.tsx
- frontend/app/_layout.tsx
- frontend/auth/provider.tsx
- frontend/auth/store.ts
- frontend/design-system/base/theme.ts
- frontend/types/mode.ts
> feat: add mechanism to switch between two themes

- docs/ARCHITECTURE.md
- docs/BACKEND.md
> minor docs fix

- frontend/app/(auth)/index.tsx
- frontend/app/_layout.tsx
- frontend/auth/provider.tsx
- frontend/auth/store.ts
- frontend/design-system/base/theme.ts
> feat: functional theme switching for dual user flow

- docs/ARCHITECTURE.md
> update arch.md to reflect latest fe changes

- frontend/auth/service.ts
> remove log statement

- backend/src/entities/schema.ts
- backend/src/entities/users/controller.ts
- backend/src/entities/users/service.ts
- backend/src/entities/users/transaction.ts
- backend/src/migrations/20250109160422_sparkling_doorman.sql
- backend/src/migrations/meta/20250109160422_snapshot.json
- backend/src/migrations/meta/_journal.json
- backend/src/tests/user/create.test.ts
- backend/src/tests/user/device.test.ts
- backend/src/tests/user/full.test.ts
- backend/src/tests/user/get.test.ts
- backend/src/types/api/routes/users.ts
- openapi.yaml
> feat: apply normalization on devices and media in db schema

- backend/src/database/reset.ts
> 🤫 fix: suppress noisy logs in test

- backend/src/server.ts
- openapi.yaml
> 😎 making api docs cooler by grouping

- README.md
Added some extra info to the readme to help others with setup.
> Updated the readme to include docker

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
> chore: remove should-run checkmarks for CI since it's redundant

- README.md
- backend/scripts/generate.ts
- backend/src/types/api/routes/users.ts
- frontend/api/client.ts
- frontend/api/device.ts
- frontend/api/user.ts
> Refinement

- backend/src/tests/groups/create.test.ts
- backend/src/tests/users/create.test.ts
- Used the global constants in tests so we don't have to modify tests if these values change.
> whoops forgot to fix global constant validation in tests

- .github/workflows/codeql.yml
- CONTRIBUTING.md
- backend/package.json
- taskfile.yaml
> add task for running drizzle studio locally

- backend/scripts/test.sh
- taskfile.yaml
> Testscript

- backend/src/entities/groups/transaction.ts
- backend/src/tests/groups/delete.test.ts
- backend/src/tests/groups/get.test.ts
> remove console.log and TODO

- .dockerignore
- .github/workflows/build.yml
- Dockerfile
- backend/bun.lock
- flake.nix
- frontend/bun.lock
- scripts/bun.sh
- scripts/deployment.sh
> Backend deployment

- README.md
> fix readme badge

- .github/workflows/deployment.yml
> fix: add more env keys for deployment

- backend/src/routes/webhook.ts
> fix: error handling for dearly bot webhook in slack

- backend/src/migrations/20250216182108_pretty_thunderball.sql
> 🛠️ fix: add nudge FK constraint to migration file

- frontend/app/(auth)/design-system.tsx
- frontend/design-system/base/button.tsx
- frontend/design-system/components/comments/bottom-sheet.tsx
- frontend/design-system/components/posts/carousel.tsx
- frontend/design-system/components/ui/icon.tsx
- frontend/design-system/components/ui/input.tsx
- Allow for dragging bottom sheet to dismiss it
- Double tab for liking the post 
- Fix text input component to take in icons that can be pressed to trigger an action
> enhance components based on all hands feedback

- backend/src/entities/groups/transaction.ts
- backend/src/services/notification/expo.ts
- backend/src/services/notification/service.ts
- backend/src/services/notification/transaction.ts
- backend/src/tests/helpers/test-constants.ts
- backend/src/tests/services/notifications.test.ts
- backend/src/utilities/errors/service-error.ts
- backend/src/utilities/query.ts
- cherry pick from nudge-group branch for fixing notification error to not crash the server
- fix database query and add more unit tests surrounding and closer to the bug 
- might need to be fixed, we'll see how it performs when deployed
- fix fetching photo carousel bug
> 🐞 fix: notification service + post feed bug

- frontend/app/(app)/_layout.tsx
- frontend/app/(app)/user/[id].tsx
- frontend/app/(app)/user/_layout.tsx
- frontend/app/(app)/user/mode.tsx
- frontend/design-system/components/groups/create-group-form.tsx
- frontend/design-system/components/shared/settings/setting.tsx
- frontend/hooks/api/user.ts
- add switching between user modes in settings
- integrate backend to update user mode in database
- update global state for user when switching between modes
> 👤 feat: switch between advanced and basic mode

- backend/src/services/init.ts
- backend/src/services/nudgeScheduler.ts
- backend/src/tests/services/nudgeScheduler.test.ts
> 🐛 fix: eventbridge scheduler to invoke lambda

- frontend/contexts/notification.tsx
> 🔔 feat: app navigation when push notification clicked

- backend/src/entities/members/transaction.ts
- frontend/app/(app)/group/switch.tsx
- frontend/app/(app)/settings/index.tsx
- frontend/design-system/components/shared/settings/setting.tsx
- frontend/design-system/components/shared/shadow.tsx
> 🐞 fix: member leaving group bug
